//YOUR FIRE BASE LINKS
var firebaseConfig = {
    apiKey: "AIzaSyDeO2w9bzAxsqXm_pIbVciYeDgJJealuR0",
    authDomain: "kwitter-ed697.firebaseapp.com",
    databaseURL: "https://kwitter-ed697-default-rtdb.firebaseio.com",
    projectId: "kwitter-ed697",
    storageBucket: "kwitter-ed697.appspot.com",
    messagingSenderId: "350160828264",
    appId: "1:350160828264:web:bd8dce810cf39431e008dd",
    measurementId: "G-NHB23CDGLX"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  //taking username and room name and storing it inside the variables 
user_name = localStorage.getItem("user_name");
room_name = localStorage.getItem("room_name");

function send()
{
msg = document.getElementById("msg").value;
firebase.database().ref(room_name).push(
      {
  name:user_name,
  message:msg,
  likes:0
    }
  );

document.getElementById("msg").value = "";
}

function getData() 
{
   firebase.database().ref("/"+room_name).on('value', function(snapshot)
    { document.getElementById("output").innerHTML = "";
     snapshot.forEach(function(childSnapshot) 
     {
        childKey  = childSnapshot.key;
         childData = childSnapshot.val(); 
         if(childKey != "purpose")
          {
        firebase_message_id = childKey;
        message_data = childData;//messagedatA: holds usernames,likes and messages
//Start code
     console.log("this is Unique message id:" +firebase_message_id);//firebase_message_id variable to hold all the unique message id  generated by the firebase
       console.log( message_data);//message_data variable to hold all the messages, likes and username for every message
       name1 = message_data["name"];
       message = message_data['message'];
     like = message_data['like'];
     name_with_tag = "<h4> "+ name1 +"<img class='user_tick' src='tick1.png'></h4>";
     message_with_tag = "<h4 class='message_h4'>" + message + "</h4>";
      like_button ="<button class='btn btn-warning' id="+firebase_message_id+" value="+like+" onclick='updateLike(this.id)'>";
     span_with_tag = "<span class='glyphicon glyphicon-thumbs-up'>Like: "+ like +"</span></button><hr>";

    row = name_with_tag + message_with_tag +like_button + span_with_tag;       
    document.getElementById("output").innerHTML += row;
//End code
  } });  }); }
getData();

function updateLike(message_id)
{
console.log("clicked on like button - " + message_id);
button_id = message_id;
likes = document.getElementById(button_id).value;
updated_likes = Number(likes) + 1;
console.log(updated_likes);

firebase.database().ref(room_name).child(message_id).update({
    like : updated_likes  
 });

}

function logout() {
localStorage.removeItem("user_name");
localStorage.removeItem("room_name");
window.location.replace("kwitter.html");
}